const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf8');

// Clean up duplicate or messy classes generated by naive replace
code = code.replace(/bg-white\/80 backdrop-blur-md bg-white\/80 border-b border-slate-200 border-b border-slate-200/g, 'bg-white/90 backdrop-blur-md border-b border-slate-200');
code = code.replace(/shadow-lg shadow-lg/g, 'shadow-lg');
code = code.replace(/shadow-sm rounded-3xl shadow-xl/g, 'shadow-xl rounded-2xl');
code = code.replace(/divide-slate-800\/50/g, 'divide-slate-200');
code = code.replace(/hover:bg-slate-800\/50/g, 'hover:bg-slate-50');
code = code.replace(/border-slate-950/g, 'border-white');

// Make borders consistently slate-200
code = code.replace(/border-slate-800/g, 'border-slate-200');
code = code.replace(/border-slate-700/g, 'border-slate-200');

// Additional UI cleanup for the primary content
code = code.replace(/bg-slate-50 border-2 border-slate-100/g, 'bg-slate-50 border border-slate-200');
code = code.replace(/bg-white border-2 border-slate-100/g, 'bg-white border border-slate-200');

// Text color tweaks for light mode
code = code.replace(/text-slate-200/g, 'text-slate-700');
code = code.replace(/text-slate-300/g, 'text-slate-600');
code = code.replace(/text-slate-400/g, 'text-slate-500');
code = code.replace(/text-slate-500/g, 'text-slate-500'); // stays same
code = code.replace(/text-white/g, 'text-white'); // leave actual white text (buttons)

fs.writeFileSync('src/App.tsx', code);
console.log("Cleaned up App.tsx duplicate CSS");
